version: 1
builder:
  configs:
    - platform: macos-spm
      swift_version: "6.2"
      documentation_targets:
        - Core
        - SubCommands
      custom_documentation_parameters:
        - --symbol-graph-minimum-access-level
        - package
